### ISSUE TITLE
Broken in Burp Suite Professional v2023.12.1-25776

### ISSUE THREAD

**Issue by schniggie** [irsdl/BurpSuiteSharpenerEx#19]
Failes to load:

A failure in get_rootTabbedPaneUsingMontoya() has occurred. Hopefully this will be recovered now.

**Comment by void-ll** [comment]
A failure in get_rootTabbedPaneUsingMontoya() has occurred. Hopefully this will be recovered now.
A failure in get_rootTabbedPaneUsingMontoya() has occurred. Hopefully this will be recovered now.
A failure in get_rootTabbedPaneUsingMontoya() has occurred. Hopefully this will be recovered now.
A failure in get_rootTabbedPaneUsingMontoya() has occurred. Hopefully this will be recovered now.

**Comment by irsdl** [comment]
Thanks for reporting this, I will try to investigate this to see when this is happening. Could you please mention the version of Sharpener being used or if it is from BApp Store?

**Comment by irsdl** [comment]
I have managed to see this on the latest version of Burp. I will try to fix it now.

**Comment by irsdl** [comment]
@schniggie thanks again for the report, the issue should be fixed in v4.5 in https://github.com/irsdl/BurpSuiteSharpenerEx/releases - please let me know whether it works for you.
I have released this very quickly given the latest burp suite update completely broke the extension as they have changed how the tabs were included in the main frame.

**Comment by schniggie** [comment]
@irsdl thank you [❤️](https://emojipedia.org/red-heart) so much. Can confirm it's loading and no errors/issues so far.
